### ISSUE TITLE
The problem with sleep and the interface. 

### ISSUE THREAD

**Issue by lev666** [NootInc/NootedBlue#7]
Good afternoon. I have a computer with asus z87-a + i7-4770k (haswell) + rx 590 and hd 4600 thanks to your kext on ventura. 

1) The problem I noticed right away is various flickering or occasional freezes 

2) No working sleep (even after disabling kext and clearing device propety) 

If you need any logs and such, I will be only in favour of helping the project!

**Comment by lev666** [comment]
Also forgot to mention that intel graphics runs in iqsv mode and monitors on rx 590

**Comment by lev666** [comment]
> I... don't think this is meant to work at all? I'm pretty surprised.
> 
> Zormeister is currently asleep afaik so there's no useful response you'll get for a while. Thanks for your understanding

That's okay, I'll wait, have a good night's sleep:)

**Comment by Zormeister** [comment]
Uh, what.

the HD 4600 is natively supported afaik, plus depending on what build you’re using it should panic on ‘hsw: Unsupported OS version!’

also Ventura has no kexts for Broadwell or Haswell by default, so its likely running with the VESA drivers, which, does not trigger any of the patches in the kext, and, breaks sleep

**Comment by lev666** [comment]
> Uh, what.
> 
> the HD 4600 is natively supported afaik, plus depending on what build you’re using it should panic on ‘hsw: Unsupported OS version!’
> 
> also Ventura has no kexts for Broadwell or Haswell by default, so its likely running with the VESA drivers, which, does not trigger any of the patches in the kext, and, breaks sleep

So regardless of whether the hd4600 is detected in ventura, but it still doesn't work at least in iQSV mode and I should just disable it and give up on those graphics? (Due to the lack of kext in ventura).

But then I have a question, what is the purpose of this kext?

**Comment by Zormeister** [comment]
To enable support of unsupported iGPUs, like Braswell or GT1 iGPUs

**Comment by lev666** [comment]
> To enable support of unsupported iGPUs, like Braswell or GT1 iGPUs

So I have misunderstood the point of this kext. Then I will switch on my ventura graphics and forget about it like a dream :(. Thanks for the explanation
